site_name: Документация
site_url: https://sawaplaygo.github.io/docs

theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  language: ru
  user_color_mode_toggle: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: pink
  
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.save
    - content.code.edit
    - content.heading.permalink
extra: 
  generator: false
